# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_now_playing_list_200_response_dates

    MovieNowPlayingList200ResponseDates(;
        maximum=nothing,
        minimum=nothing,
    )

    - maximum::String
    - minimum::String
"""
Base.@kwdef mutable struct MovieNowPlayingList200ResponseDates <: OpenAPI.APIModel
    maximum::Union{Nothing, String} = nothing
    minimum::Union{Nothing, String} = nothing

    function MovieNowPlayingList200ResponseDates(maximum, minimum, )
        OpenAPI.validate_property(MovieNowPlayingList200ResponseDates, Symbol("maximum"), maximum)
        OpenAPI.validate_property(MovieNowPlayingList200ResponseDates, Symbol("minimum"), minimum)
        return new(maximum, minimum, )
    end
end # type MovieNowPlayingList200ResponseDates

const _property_types_MovieNowPlayingList200ResponseDates = Dict{Symbol,String}(Symbol("maximum")=>"String", Symbol("minimum")=>"String", )
OpenAPI.property_type(::Type{ MovieNowPlayingList200ResponseDates }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieNowPlayingList200ResponseDates[name]))}

function check_required(o::MovieNowPlayingList200ResponseDates)
    true
end

function OpenAPI.validate_property(::Type{ MovieNowPlayingList200ResponseDates }, name::Symbol, val)
end
