# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_episode_translations_200_response

    TvEpisodeTranslations200Response(;
        id=0,
        translations=nothing,
    )

    - id::Int64
    - translations::Vector{TvEpisodeTranslations200ResponseTranslationsInner}
"""
Base.@kwdef mutable struct TvEpisodeTranslations200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    translations::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvEpisodeTranslations200ResponseTranslationsInner} }

    function TvEpisodeTranslations200Response(id, translations, )
        OpenAPI.validate_property(TvEpisodeTranslations200Response, Symbol("id"), id)
        OpenAPI.validate_property(TvEpisodeTranslations200Response, Symbol("translations"), translations)
        return new(id, translations, )
    end
end # type TvEpisodeTranslations200Response

const _property_types_TvEpisodeTranslations200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("translations")=>"Vector{TvEpisodeTranslations200ResponseTranslationsInner}", )
OpenAPI.property_type(::Type{ TvEpisodeTranslations200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvEpisodeTranslations200Response[name]))}

function check_required(o::TvEpisodeTranslations200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvEpisodeTranslations200Response }, name::Symbol, val)
end
