# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""account_details_200_response_avatar_gravatar

    AccountDetails200ResponseAvatarGravatar(;
        hash=nothing,
    )

    - hash::String
"""
Base.@kwdef mutable struct AccountDetails200ResponseAvatarGravatar <: OpenAPI.APIModel
    hash::Union{Nothing, String} = nothing

    function AccountDetails200ResponseAvatarGravatar(hash, )
        OpenAPI.validate_property(AccountDetails200ResponseAvatarGravatar, Symbol("hash"), hash)
        return new(hash, )
    end
end # type AccountDetails200ResponseAvatarGravatar

const _property_types_AccountDetails200ResponseAvatarGravatar = Dict{Symbol,String}(Symbol("hash")=>"String", )
OpenAPI.property_type(::Type{ AccountDetails200ResponseAvatarGravatar }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountDetails200ResponseAvatarGravatar[name]))}

function check_required(o::AccountDetails200ResponseAvatarGravatar)
    true
end

function OpenAPI.validate_property(::Type{ AccountDetails200ResponseAvatarGravatar }, name::Symbol, val)
end
