# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_add_items_200_response_results_inner

    ListAddItems200ResponseResultsInner(;
        media_type=nothing,
        media_id=0,
        success=true,
    )

    - media_type::String
    - media_id::Int64
    - success::Bool
"""
Base.@kwdef mutable struct ListAddItems200ResponseResultsInner <: OpenAPI.APIModel
    media_type::Union{Nothing, String} = nothing
    media_id::Union{Nothing, Int64} = 0
    success::Union{Nothing, Bool} = true

    function ListAddItems200ResponseResultsInner(media_type, media_id, success, )
        OpenAPI.validate_property(ListAddItems200ResponseResultsInner, Symbol("media_type"), media_type)
        OpenAPI.validate_property(ListAddItems200ResponseResultsInner, Symbol("media_id"), media_id)
        OpenAPI.validate_property(ListAddItems200ResponseResultsInner, Symbol("success"), success)
        return new(media_type, media_id, success, )
    end
end # type ListAddItems200ResponseResultsInner

const _property_types_ListAddItems200ResponseResultsInner = Dict{Symbol,String}(Symbol("media_type")=>"String", Symbol("media_id")=>"Int64", Symbol("success")=>"Bool", )
OpenAPI.property_type(::Type{ ListAddItems200ResponseResultsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListAddItems200ResponseResultsInner[name]))}

function check_required(o::ListAddItems200ResponseResultsInner)
    true
end

function OpenAPI.validate_property(::Type{ ListAddItems200ResponseResultsInner }, name::Symbol, val)
end
