# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_IN

    MovieWatchProviders200ResponseResultsIN(;
        link=nothing,
        flatrate=nothing,
        rent=nothing,
        buy=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsINRentInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsINRentInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsIN <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsINRentInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsINRentInner} }

    function MovieWatchProviders200ResponseResultsIN(link, flatrate, rent, buy, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIN, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIN, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIN, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIN, Symbol("buy"), buy)
        return new(link, flatrate, rent, buy, )
    end
end # type MovieWatchProviders200ResponseResultsIN

const _property_types_MovieWatchProviders200ResponseResultsIN = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsINRentInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsINRentInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsIN }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsIN[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsIN)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsIN }, name::Symbol, val)
end
