# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_changes_200_response_changes_inner_items_inner_value_poster

    MovieChanges200ResponseChangesInnerItemsInnerValuePoster(;
        file_path=nothing,
    )

    - file_path::String
"""
Base.@kwdef mutable struct MovieChanges200ResponseChangesInnerItemsInnerValuePoster <: OpenAPI.APIModel
    file_path::Union{Nothing, String} = nothing

    function MovieChanges200ResponseChangesInnerItemsInnerValuePoster(file_path, )
        OpenAPI.validate_property(MovieChanges200ResponseChangesInnerItemsInnerValuePoster, Symbol("file_path"), file_path)
        return new(file_path, )
    end
end # type MovieChanges200ResponseChangesInnerItemsInnerValuePoster

const _property_types_MovieChanges200ResponseChangesInnerItemsInnerValuePoster = Dict{Symbol,String}(Symbol("file_path")=>"String", )
OpenAPI.property_type(::Type{ MovieChanges200ResponseChangesInnerItemsInnerValuePoster }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieChanges200ResponseChangesInnerItemsInnerValuePoster[name]))}

function check_required(o::MovieChanges200ResponseChangesInnerItemsInnerValuePoster)
    true
end

function OpenAPI.validate_property(::Type{ MovieChanges200ResponseChangesInnerItemsInnerValuePoster }, name::Symbol, val)
end
