# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""account_rated_tv_episodes_200_response_results_inner

    AccountRatedTvEpisodes200ResponseResultsInner(;
        air_date=nothing,
        episode_number=0,
        id=0,
        name=nothing,
        overview=nothing,
        production_code=nothing,
        runtime=0,
        season_number=0,
        show_id=0,
        still_path=nothing,
        vote_average=0,
        vote_count=0,
        rating=0,
    )

    - air_date::String
    - episode_number::Int64
    - id::Int64
    - name::String
    - overview::String
    - production_code::String
    - runtime::Int64
    - season_number::Int64
    - show_id::Int64
    - still_path::String
    - vote_average::Float64
    - vote_count::Int64
    - rating::Int64
"""
Base.@kwdef mutable struct AccountRatedTvEpisodes200ResponseResultsInner <: OpenAPI.APIModel
    air_date::Union{Nothing, String} = nothing
    episode_number::Union{Nothing, Int64} = 0
    id::Union{Nothing, Int64} = 0
    name::Union{Nothing, String} = nothing
    overview::Union{Nothing, String} = nothing
    production_code::Union{Nothing, String} = nothing
    runtime::Union{Nothing, Int64} = 0
    season_number::Union{Nothing, Int64} = 0
    show_id::Union{Nothing, Int64} = 0
    still_path::Union{Nothing, String} = nothing
    vote_average::Union{Nothing, Float64} = 0
    vote_count::Union{Nothing, Int64} = 0
    rating::Union{Nothing, Int64} = 0

    function AccountRatedTvEpisodes200ResponseResultsInner(air_date, episode_number, id, name, overview, production_code, runtime, season_number, show_id, still_path, vote_average, vote_count, rating, )
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("air_date"), air_date)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("episode_number"), episode_number)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("id"), id)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("name"), name)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("overview"), overview)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("production_code"), production_code)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("runtime"), runtime)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("season_number"), season_number)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("show_id"), show_id)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("still_path"), still_path)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("vote_average"), vote_average)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("vote_count"), vote_count)
        OpenAPI.validate_property(AccountRatedTvEpisodes200ResponseResultsInner, Symbol("rating"), rating)
        return new(air_date, episode_number, id, name, overview, production_code, runtime, season_number, show_id, still_path, vote_average, vote_count, rating, )
    end
end # type AccountRatedTvEpisodes200ResponseResultsInner

const _property_types_AccountRatedTvEpisodes200ResponseResultsInner = Dict{Symbol,String}(Symbol("air_date")=>"String", Symbol("episode_number")=>"Int64", Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("overview")=>"String", Symbol("production_code")=>"String", Symbol("runtime")=>"Int64", Symbol("season_number")=>"Int64", Symbol("show_id")=>"Int64", Symbol("still_path")=>"String", Symbol("vote_average")=>"Float64", Symbol("vote_count")=>"Int64", Symbol("rating")=>"Int64", )
OpenAPI.property_type(::Type{ AccountRatedTvEpisodes200ResponseResultsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountRatedTvEpisodes200ResponseResultsInner[name]))}

function check_required(o::AccountRatedTvEpisodes200ResponseResultsInner)
    true
end

function OpenAPI.validate_property(::Type{ AccountRatedTvEpisodes200ResponseResultsInner }, name::Symbol, val)
end
