# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_videos_200_response

    MovieVideos200Response(;
        id=0,
        results=nothing,
    )

    - id::Int64
    - results::Vector{MovieVideos200ResponseResultsInner}
"""
Base.@kwdef mutable struct MovieVideos200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    results::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieVideos200ResponseResultsInner} }

    function MovieVideos200Response(id, results, )
        OpenAPI.validate_property(MovieVideos200Response, Symbol("id"), id)
        OpenAPI.validate_property(MovieVideos200Response, Symbol("results"), results)
        return new(id, results, )
    end
end # type MovieVideos200Response

const _property_types_MovieVideos200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("results")=>"Vector{MovieVideos200ResponseResultsInner}", )
OpenAPI.property_type(::Type{ MovieVideos200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieVideos200Response[name]))}

function check_required(o::MovieVideos200Response)
    true
end

function OpenAPI.validate_property(::Type{ MovieVideos200Response }, name::Symbol, val)
end
