# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_SK

    MovieWatchProviders200ResponseResultsSK(;
        link=nothing,
        buy=nothing,
        flatrate=nothing,
        rent=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsCZBuyInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsCZBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsSK <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCZBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCZBuyInner} }

    function MovieWatchProviders200ResponseResultsSK(link, buy, flatrate, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSK, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSK, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSK, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSK, Symbol("rent"), rent)
        return new(link, buy, flatrate, rent, )
    end
end # type MovieWatchProviders200ResponseResultsSK

const _property_types_MovieWatchProviders200ResponseResultsSK = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsCZBuyInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsCZBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsSK }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsSK[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsSK)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsSK }, name::Symbol, val)
end
