# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_changes_200_response_changes_inner_items_inner_value_poster

    TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster(;
        file_path=nothing,
        iso_639_1=nothing,
    )

    - file_path::String
    - iso_639_1::String
"""
Base.@kwdef mutable struct TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster <: OpenAPI.APIModel
    file_path::Union{Nothing, String} = nothing
    iso_639_1::Union{Nothing, String} = nothing

    function TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster(file_path, iso_639_1, )
        OpenAPI.validate_property(TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster, Symbol("file_path"), file_path)
        OpenAPI.validate_property(TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster, Symbol("iso_639_1"), iso_639_1)
        return new(file_path, iso_639_1, )
    end
end # type TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster

const _property_types_TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster = Dict{Symbol,String}(Symbol("file_path")=>"String", Symbol("iso_639_1")=>"String", )
OpenAPI.property_type(::Type{ TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster[name]))}

function check_required(o::TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesChanges200ResponseChangesInnerItemsInnerValuePoster }, name::Symbol, val)
end
