# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""certifications_tv_list_200_response

    CertificationsTvList200Response(;
        certifications=nothing,
    )

    - certifications::CertificationsTvList200ResponseCertifications
"""
Base.@kwdef mutable struct CertificationsTvList200Response <: OpenAPI.APIModel
    certifications = nothing # spec type: Union{ Nothing, CertificationsTvList200ResponseCertifications }

    function CertificationsTvList200Response(certifications, )
        OpenAPI.validate_property(CertificationsTvList200Response, Symbol("certifications"), certifications)
        return new(certifications, )
    end
end # type CertificationsTvList200Response

const _property_types_CertificationsTvList200Response = Dict{Symbol,String}(Symbol("certifications")=>"CertificationsTvList200ResponseCertifications", )
OpenAPI.property_type(::Type{ CertificationsTvList200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CertificationsTvList200Response[name]))}

function check_required(o::CertificationsTvList200Response)
    true
end

function OpenAPI.validate_property(::Type{ CertificationsTvList200Response }, name::Symbol, val)
end
