# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_KR

    MovieWatchProviders200ResponseResultsKR(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsKRBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsKR <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsKRBuyInner} }

    function MovieWatchProviders200ResponseResultsKR(link, flatrate, buy, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsKR, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsKR, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsKR, Symbol("buy"), buy)
        return new(link, flatrate, buy, )
    end
end # type MovieWatchProviders200ResponseResultsKR

const _property_types_MovieWatchProviders200ResponseResultsKR = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsKRBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsKR }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsKR[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsKR)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsKR }, name::Symbol, val)
end
