# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_delete_rating_200_response

    MovieDeleteRating200Response(;
        status_code=0,
        status_message=nothing,
    )

    - status_code::Int64
    - status_message::String
"""
Base.@kwdef mutable struct MovieDeleteRating200Response <: OpenAPI.APIModel
    status_code::Union{Nothing, Int64} = 0
    status_message::Union{Nothing, String} = nothing

    function MovieDeleteRating200Response(status_code, status_message, )
        OpenAPI.validate_property(MovieDeleteRating200Response, Symbol("status_code"), status_code)
        OpenAPI.validate_property(MovieDeleteRating200Response, Symbol("status_message"), status_message)
        return new(status_code, status_message, )
    end
end # type MovieDeleteRating200Response

const _property_types_MovieDeleteRating200Response = Dict{Symbol,String}(Symbol("status_code")=>"Int64", Symbol("status_message")=>"String", )
OpenAPI.property_type(::Type{ MovieDeleteRating200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieDeleteRating200Response[name]))}

function check_required(o::MovieDeleteRating200Response)
    true
end

function OpenAPI.validate_property(::Type{ MovieDeleteRating200Response }, name::Symbol, val)
end
