# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_PK

    MovieWatchProviders200ResponseResultsPK(;
        link=nothing,
        flatrate=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsPKFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsPK <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsPKFlatrateInner} }

    function MovieWatchProviders200ResponseResultsPK(link, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPK, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPK, Symbol("flatrate"), flatrate)
        return new(link, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsPK

const _property_types_MovieWatchProviders200ResponseResultsPK = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsPKFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsPK }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsPK[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsPK)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsPK }, name::Symbol, val)
end
