# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_FI

    MovieWatchProviders200ResponseResultsFI(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsAUBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsAUBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsFI <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUBuyInner} }

    function MovieWatchProviders200ResponseResultsFI(link, flatrate, buy, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFI, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFI, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFI, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFI, Symbol("rent"), rent)
        return new(link, flatrate, buy, rent, )
    end
end # type MovieWatchProviders200ResponseResultsFI

const _property_types_MovieWatchProviders200ResponseResultsFI = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsAUBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsAUBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsFI }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsFI[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsFI)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsFI }, name::Symbol, val)
end
