# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_BR

    MovieWatchProviders200ResponseResultsBR(;
        link=nothing,
        flatrate=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsBR <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsARFlatrateInner} }

    function MovieWatchProviders200ResponseResultsBR(link, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsBR, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsBR, Symbol("flatrate"), flatrate)
        return new(link, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsBR

const _property_types_MovieWatchProviders200ResponseResultsBR = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsBR }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsBR[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsBR)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsBR }, name::Symbol, val)
end
