# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""account_tv_recommendations_200_response_results_inner

    AccountTvRecommendations200ResponseResultsInner(;
        adult=true,
        backdrop_path=nothing,
        id=0,
        name=nothing,
        original_language=nothing,
        original_name=nothing,
        overview=nothing,
        poster_path=nothing,
        media_type=nothing,
        genre_ids=nothing,
        popularity=0,
        first_air_date=nothing,
        vote_average=0,
        vote_count=0,
        origin_country=nothing,
    )

    - adult::Bool
    - backdrop_path::String
    - id::Int64
    - name::String
    - original_language::String
    - original_name::String
    - overview::String
    - poster_path::String
    - media_type::String
    - genre_ids::Vector{Int64}
    - popularity::Float64
    - first_air_date::String
    - vote_average::Float64
    - vote_count::Int64
    - origin_country::Vector{String}
"""
Base.@kwdef mutable struct AccountTvRecommendations200ResponseResultsInner <: OpenAPI.APIModel
    adult::Union{Nothing, Bool} = true
    backdrop_path::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = 0
    name::Union{Nothing, String} = nothing
    original_language::Union{Nothing, String} = nothing
    original_name::Union{Nothing, String} = nothing
    overview::Union{Nothing, String} = nothing
    poster_path::Union{Nothing, String} = nothing
    media_type::Union{Nothing, String} = nothing
    genre_ids::Union{Nothing, Vector{Int64}} = nothing
    popularity::Union{Nothing, Float64} = 0
    first_air_date::Union{Nothing, String} = nothing
    vote_average::Union{Nothing, Float64} = 0
    vote_count::Union{Nothing, Int64} = 0
    origin_country::Union{Nothing, Vector{String}} = nothing

    function AccountTvRecommendations200ResponseResultsInner(adult, backdrop_path, id, name, original_language, original_name, overview, poster_path, media_type, genre_ids, popularity, first_air_date, vote_average, vote_count, origin_country, )
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("adult"), adult)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("backdrop_path"), backdrop_path)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("id"), id)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("name"), name)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("original_language"), original_language)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("original_name"), original_name)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("overview"), overview)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("poster_path"), poster_path)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("media_type"), media_type)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("genre_ids"), genre_ids)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("popularity"), popularity)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("first_air_date"), first_air_date)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("vote_average"), vote_average)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("vote_count"), vote_count)
        OpenAPI.validate_property(AccountTvRecommendations200ResponseResultsInner, Symbol("origin_country"), origin_country)
        return new(adult, backdrop_path, id, name, original_language, original_name, overview, poster_path, media_type, genre_ids, popularity, first_air_date, vote_average, vote_count, origin_country, )
    end
end # type AccountTvRecommendations200ResponseResultsInner

const _property_types_AccountTvRecommendations200ResponseResultsInner = Dict{Symbol,String}(Symbol("adult")=>"Bool", Symbol("backdrop_path")=>"String", Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("original_language")=>"String", Symbol("original_name")=>"String", Symbol("overview")=>"String", Symbol("poster_path")=>"String", Symbol("media_type")=>"String", Symbol("genre_ids")=>"Vector{Int64}", Symbol("popularity")=>"Float64", Symbol("first_air_date")=>"String", Symbol("vote_average")=>"Float64", Symbol("vote_count")=>"Int64", Symbol("origin_country")=>"Vector{String}", )
OpenAPI.property_type(::Type{ AccountTvRecommendations200ResponseResultsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountTvRecommendations200ResponseResultsInner[name]))}

function check_required(o::AccountTvRecommendations200ResponseResultsInner)
    true
end

function OpenAPI.validate_property(::Type{ AccountTvRecommendations200ResponseResultsInner }, name::Symbol, val)
end
