# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""review_details_200_response_author_details

    ReviewDetails200ResponseAuthorDetails(;
        name=nothing,
        username=nothing,
        avatar_path=nothing,
        rating=0,
    )

    - name::String
    - username::String
    - avatar_path::String
    - rating::Int64
"""
Base.@kwdef mutable struct ReviewDetails200ResponseAuthorDetails <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    username::Union{Nothing, String} = nothing
    avatar_path::Union{Nothing, String} = nothing
    rating::Union{Nothing, Int64} = 0

    function ReviewDetails200ResponseAuthorDetails(name, username, avatar_path, rating, )
        OpenAPI.validate_property(ReviewDetails200ResponseAuthorDetails, Symbol("name"), name)
        OpenAPI.validate_property(ReviewDetails200ResponseAuthorDetails, Symbol("username"), username)
        OpenAPI.validate_property(ReviewDetails200ResponseAuthorDetails, Symbol("avatar_path"), avatar_path)
        OpenAPI.validate_property(ReviewDetails200ResponseAuthorDetails, Symbol("rating"), rating)
        return new(name, username, avatar_path, rating, )
    end
end # type ReviewDetails200ResponseAuthorDetails

const _property_types_ReviewDetails200ResponseAuthorDetails = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("username")=>"String", Symbol("avatar_path")=>"String", Symbol("rating")=>"Int64", )
OpenAPI.property_type(::Type{ ReviewDetails200ResponseAuthorDetails }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReviewDetails200ResponseAuthorDetails[name]))}

function check_required(o::ReviewDetails200ResponseAuthorDetails)
    true
end

function OpenAPI.validate_property(::Type{ ReviewDetails200ResponseAuthorDetails }, name::Symbol, val)
end
