# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response_results_NO

    TvSeriesWatchProviders200ResponseResultsNO(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
    )

    - link::String
    - flatrate::Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner}
    - buy::Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner}
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200ResponseResultsNO <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner} }

    function TvSeriesWatchProviders200ResponseResultsNO(link, flatrate, buy, )
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsNO, Symbol("link"), link)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsNO, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsNO, Symbol("buy"), buy)
        return new(link, flatrate, buy, )
    end
end # type TvSeriesWatchProviders200ResponseResultsNO

const _property_types_TvSeriesWatchProviders200ResponseResultsNO = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner}", Symbol("buy")=>"Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner}", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200ResponseResultsNO }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200ResponseResultsNO[name]))}

function check_required(o::TvSeriesWatchProviders200ResponseResultsNO)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200ResponseResultsNO }, name::Symbol, val)
end
