# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_ES

    MovieWatchProviders200ResponseResultsES(;
        link=nothing,
        rent=nothing,
        ads=nothing,
        flatrate=nothing,
        buy=nothing,
    )

    - link::String
    - rent::Vector{MovieWatchProviders200ResponseResultsDEBuyInner}
    - ads::Vector{MovieWatchProviders200ResponseResultsESAdsInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsDEBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsES <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsDEBuyInner} }
    ads::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsESAdsInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsDEBuyInner} }

    function MovieWatchProviders200ResponseResultsES(link, rent, ads, flatrate, buy, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsES, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsES, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsES, Symbol("ads"), ads)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsES, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsES, Symbol("buy"), buy)
        return new(link, rent, ads, flatrate, buy, )
    end
end # type MovieWatchProviders200ResponseResultsES

const _property_types_MovieWatchProviders200ResponseResultsES = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsDEBuyInner}", Symbol("ads")=>"Vector{MovieWatchProviders200ResponseResultsESAdsInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsDEBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsES }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsES[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsES)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsES }, name::Symbol, val)
end
