# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_credits_200_response_crew_inner

    TvSeasonCredits200ResponseCrewInner(;
        adult=true,
        gender=0,
        id=0,
        known_for_department=nothing,
        name=nothing,
        original_name=nothing,
        popularity=0,
        profile_path=nothing,
        credit_id=nothing,
        department=nothing,
        job=nothing,
    )

    - adult::Bool
    - gender::Int64
    - id::Int64
    - known_for_department::String
    - name::String
    - original_name::String
    - popularity::Float64
    - profile_path::Any
    - credit_id::String
    - department::String
    - job::String
"""
Base.@kwdef mutable struct TvSeasonCredits200ResponseCrewInner <: OpenAPI.APIModel
    adult::Union{Nothing, Bool} = true
    gender::Union{Nothing, Int64} = 0
    id::Union{Nothing, Int64} = 0
    known_for_department::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    original_name::Union{Nothing, String} = nothing
    popularity::Union{Nothing, Float64} = 0
    profile_path::Union{Nothing, Any} = nothing
    credit_id::Union{Nothing, String} = nothing
    department::Union{Nothing, String} = nothing
    job::Union{Nothing, String} = nothing

    function TvSeasonCredits200ResponseCrewInner(adult, gender, id, known_for_department, name, original_name, popularity, profile_path, credit_id, department, job, )
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("adult"), adult)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("gender"), gender)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("id"), id)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("known_for_department"), known_for_department)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("name"), name)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("original_name"), original_name)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("popularity"), popularity)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("profile_path"), profile_path)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("credit_id"), credit_id)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("department"), department)
        OpenAPI.validate_property(TvSeasonCredits200ResponseCrewInner, Symbol("job"), job)
        return new(adult, gender, id, known_for_department, name, original_name, popularity, profile_path, credit_id, department, job, )
    end
end # type TvSeasonCredits200ResponseCrewInner

const _property_types_TvSeasonCredits200ResponseCrewInner = Dict{Symbol,String}(Symbol("adult")=>"Bool", Symbol("gender")=>"Int64", Symbol("id")=>"Int64", Symbol("known_for_department")=>"String", Symbol("name")=>"String", Symbol("original_name")=>"String", Symbol("popularity")=>"Float64", Symbol("profile_path")=>"Any", Symbol("credit_id")=>"String", Symbol("department")=>"String", Symbol("job")=>"String", )
OpenAPI.property_type(::Type{ TvSeasonCredits200ResponseCrewInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonCredits200ResponseCrewInner[name]))}

function check_required(o::TvSeasonCredits200ResponseCrewInner)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonCredits200ResponseCrewInner }, name::Symbol, val)
end
