# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_create_200_response

    ListCreate200Response(;
        status_message=nothing,
        success=true,
        status_code=0,
        list_id=0,
    )

    - status_message::String
    - success::Bool
    - status_code::Int64
    - list_id::Int64
"""
Base.@kwdef mutable struct ListCreate200Response <: OpenAPI.APIModel
    status_message::Union{Nothing, String} = nothing
    success::Union{Nothing, Bool} = true
    status_code::Union{Nothing, Int64} = 0
    list_id::Union{Nothing, Int64} = 0

    function ListCreate200Response(status_message, success, status_code, list_id, )
        OpenAPI.validate_property(ListCreate200Response, Symbol("status_message"), status_message)
        OpenAPI.validate_property(ListCreate200Response, Symbol("success"), success)
        OpenAPI.validate_property(ListCreate200Response, Symbol("status_code"), status_code)
        OpenAPI.validate_property(ListCreate200Response, Symbol("list_id"), list_id)
        return new(status_message, success, status_code, list_id, )
    end
end # type ListCreate200Response

const _property_types_ListCreate200Response = Dict{Symbol,String}(Symbol("status_message")=>"String", Symbol("success")=>"Bool", Symbol("status_code")=>"Int64", Symbol("list_id")=>"Int64", )
OpenAPI.property_type(::Type{ ListCreate200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListCreate200Response[name]))}

function check_required(o::ListCreate200Response)
    true
end

function OpenAPI.validate_property(::Type{ ListCreate200Response }, name::Symbol, val)
end
