# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""details_copy_200_response_results_inner

    DetailsCopy200ResponseResultsInner(;
        name=nothing,
        type=nothing,
    )

    - name::String
    - type::String
"""
Base.@kwdef mutable struct DetailsCopy200ResponseResultsInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing

    function DetailsCopy200ResponseResultsInner(name, type, )
        OpenAPI.validate_property(DetailsCopy200ResponseResultsInner, Symbol("name"), name)
        OpenAPI.validate_property(DetailsCopy200ResponseResultsInner, Symbol("type"), type)
        return new(name, type, )
    end
end # type DetailsCopy200ResponseResultsInner

const _property_types_DetailsCopy200ResponseResultsInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ DetailsCopy200ResponseResultsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DetailsCopy200ResponseResultsInner[name]))}

function check_required(o::DetailsCopy200ResponseResultsInner)
    true
end

function OpenAPI.validate_property(::Type{ DetailsCopy200ResponseResultsInner }, name::Symbol, val)
end
