# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_videos_200_response

    TvSeriesVideos200Response(;
        id=0,
        results=nothing,
    )

    - id::Int64
    - results::Vector{TvSeriesVideos200ResponseResultsInner}
"""
Base.@kwdef mutable struct TvSeriesVideos200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    results::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesVideos200ResponseResultsInner} }

    function TvSeriesVideos200Response(id, results, )
        OpenAPI.validate_property(TvSeriesVideos200Response, Symbol("id"), id)
        OpenAPI.validate_property(TvSeriesVideos200Response, Symbol("results"), results)
        return new(id, results, )
    end
end # type TvSeriesVideos200Response

const _property_types_TvSeriesVideos200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("results")=>"Vector{TvSeriesVideos200ResponseResultsInner}", )
OpenAPI.property_type(::Type{ TvSeriesVideos200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesVideos200Response[name]))}

function check_required(o::TvSeriesVideos200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesVideos200Response }, name::Symbol, val)
end
