# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_PE

    MovieWatchProviders200ResponseResultsPE(;
        link=nothing,
        rent=nothing,
        buy=nothing,
        flatrate=nothing,
    )

    - link::String
    - rent::Vector{MovieWatchProviders200ResponseResultsPERentInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsPERentInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsPE <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsPERentInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsPERentInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsARFlatrateInner} }

    function MovieWatchProviders200ResponseResultsPE(link, rent, buy, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPE, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPE, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPE, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPE, Symbol("flatrate"), flatrate)
        return new(link, rent, buy, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsPE

const _property_types_MovieWatchProviders200ResponseResultsPE = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsPERentInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsPERentInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsPE }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsPE[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsPE)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsPE }, name::Symbol, val)
end
