# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_episode_details_200_response_guest_stars_inner

    TvEpisodeDetails200ResponseGuestStarsInner(;
        character=nothing,
        credit_id=nothing,
        order=0,
        adult=true,
        gender=0,
        id=0,
        known_for_department=nothing,
        name=nothing,
        original_name=nothing,
        popularity=0,
        profile_path=nothing,
    )

    - character::String
    - credit_id::String
    - order::Int64
    - adult::Bool
    - gender::Int64
    - id::Int64
    - known_for_department::String
    - name::String
    - original_name::String
    - popularity::Float64
    - profile_path::String
"""
Base.@kwdef mutable struct TvEpisodeDetails200ResponseGuestStarsInner <: OpenAPI.APIModel
    character::Union{Nothing, String} = nothing
    credit_id::Union{Nothing, String} = nothing
    order::Union{Nothing, Int64} = 0
    adult::Union{Nothing, Bool} = true
    gender::Union{Nothing, Int64} = 0
    id::Union{Nothing, Int64} = 0
    known_for_department::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    original_name::Union{Nothing, String} = nothing
    popularity::Union{Nothing, Float64} = 0
    profile_path::Union{Nothing, String} = nothing

    function TvEpisodeDetails200ResponseGuestStarsInner(character, credit_id, order, adult, gender, id, known_for_department, name, original_name, popularity, profile_path, )
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("character"), character)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("credit_id"), credit_id)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("order"), order)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("adult"), adult)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("gender"), gender)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("id"), id)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("known_for_department"), known_for_department)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("name"), name)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("original_name"), original_name)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("popularity"), popularity)
        OpenAPI.validate_property(TvEpisodeDetails200ResponseGuestStarsInner, Symbol("profile_path"), profile_path)
        return new(character, credit_id, order, adult, gender, id, known_for_department, name, original_name, popularity, profile_path, )
    end
end # type TvEpisodeDetails200ResponseGuestStarsInner

const _property_types_TvEpisodeDetails200ResponseGuestStarsInner = Dict{Symbol,String}(Symbol("character")=>"String", Symbol("credit_id")=>"String", Symbol("order")=>"Int64", Symbol("adult")=>"Bool", Symbol("gender")=>"Int64", Symbol("id")=>"Int64", Symbol("known_for_department")=>"String", Symbol("name")=>"String", Symbol("original_name")=>"String", Symbol("popularity")=>"Float64", Symbol("profile_path")=>"String", )
OpenAPI.property_type(::Type{ TvEpisodeDetails200ResponseGuestStarsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvEpisodeDetails200ResponseGuestStarsInner[name]))}

function check_required(o::TvEpisodeDetails200ResponseGuestStarsInner)
    true
end

function OpenAPI.validate_property(::Type{ TvEpisodeDetails200ResponseGuestStarsInner }, name::Symbol, val)
end
