# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_SA

    MovieWatchProviders200ResponseResultsSA(;
        link=nothing,
        flatrate=nothing,
        rent=nothing,
        buy=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsSAFlatrateInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsAERentInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsAERentInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsSA <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsSAFlatrateInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAERentInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAERentInner} }

    function MovieWatchProviders200ResponseResultsSA(link, flatrate, rent, buy, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSA, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSA, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSA, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSA, Symbol("buy"), buy)
        return new(link, flatrate, rent, buy, )
    end
end # type MovieWatchProviders200ResponseResultsSA

const _property_types_MovieWatchProviders200ResponseResultsSA = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsSAFlatrateInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsAERentInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsAERentInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsSA }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsSA[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsSA)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsSA }, name::Symbol, val)
end
