# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""list_details_200_response_items_inner

    ListDetails200ResponseItemsInner(;
        adult=true,
        backdrop_path=nothing,
        genre_ids=nothing,
        id=0,
        media_type=nothing,
        original_language=nothing,
        original_title=nothing,
        overview=nothing,
        popularity=0,
        poster_path=nothing,
        release_date=nothing,
        title=nothing,
        video=true,
        vote_average=0,
        vote_count=0,
    )

    - adult::Bool
    - backdrop_path::String
    - genre_ids::Vector{Int64}
    - id::Int64
    - media_type::String
    - original_language::String
    - original_title::String
    - overview::String
    - popularity::Float64
    - poster_path::String
    - release_date::String
    - title::String
    - video::Bool
    - vote_average::Int64
    - vote_count::Int64
"""
Base.@kwdef mutable struct ListDetails200ResponseItemsInner <: OpenAPI.APIModel
    adult::Union{Nothing, Bool} = true
    backdrop_path::Union{Nothing, String} = nothing
    genre_ids::Union{Nothing, Vector{Int64}} = nothing
    id::Union{Nothing, Int64} = 0
    media_type::Union{Nothing, String} = nothing
    original_language::Union{Nothing, String} = nothing
    original_title::Union{Nothing, String} = nothing
    overview::Union{Nothing, String} = nothing
    popularity::Union{Nothing, Float64} = 0
    poster_path::Union{Nothing, String} = nothing
    release_date::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing
    video::Union{Nothing, Bool} = true
    vote_average::Union{Nothing, Int64} = 0
    vote_count::Union{Nothing, Int64} = 0

    function ListDetails200ResponseItemsInner(adult, backdrop_path, genre_ids, id, media_type, original_language, original_title, overview, popularity, poster_path, release_date, title, video, vote_average, vote_count, )
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("adult"), adult)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("backdrop_path"), backdrop_path)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("genre_ids"), genre_ids)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("id"), id)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("media_type"), media_type)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("original_language"), original_language)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("original_title"), original_title)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("overview"), overview)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("popularity"), popularity)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("poster_path"), poster_path)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("release_date"), release_date)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("title"), title)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("video"), video)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("vote_average"), vote_average)
        OpenAPI.validate_property(ListDetails200ResponseItemsInner, Symbol("vote_count"), vote_count)
        return new(adult, backdrop_path, genre_ids, id, media_type, original_language, original_title, overview, popularity, poster_path, release_date, title, video, vote_average, vote_count, )
    end
end # type ListDetails200ResponseItemsInner

const _property_types_ListDetails200ResponseItemsInner = Dict{Symbol,String}(Symbol("adult")=>"Bool", Symbol("backdrop_path")=>"String", Symbol("genre_ids")=>"Vector{Int64}", Symbol("id")=>"Int64", Symbol("media_type")=>"String", Symbol("original_language")=>"String", Symbol("original_title")=>"String", Symbol("overview")=>"String", Symbol("popularity")=>"Float64", Symbol("poster_path")=>"String", Symbol("release_date")=>"String", Symbol("title")=>"String", Symbol("video")=>"Bool", Symbol("vote_average")=>"Int64", Symbol("vote_count")=>"Int64", )
OpenAPI.property_type(::Type{ ListDetails200ResponseItemsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListDetails200ResponseItemsInner[name]))}

function check_required(o::ListDetails200ResponseItemsInner)
    true
end

function OpenAPI.validate_property(::Type{ ListDetails200ResponseItemsInner }, name::Symbol, val)
end
