# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_watch_providers_200_response_results_NO

    TvSeasonWatchProviders200ResponseResultsNO(;
        link=nothing,
        buy=nothing,
        flatrate=nothing,
    )

    - link::String
    - buy::Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner}
    - flatrate::Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner}
"""
Base.@kwdef mutable struct TvSeasonWatchProviders200ResponseResultsNO <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner} }

    function TvSeasonWatchProviders200ResponseResultsNO(link, buy, flatrate, )
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsNO, Symbol("link"), link)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsNO, Symbol("buy"), buy)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsNO, Symbol("flatrate"), flatrate)
        return new(link, buy, flatrate, )
    end
end # type TvSeasonWatchProviders200ResponseResultsNO

const _property_types_TvSeasonWatchProviders200ResponseResultsNO = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{TvSeriesWatchProviders200ResponseResultsNOBuyInner}", Symbol("flatrate")=>"Vector{TvSeriesWatchProviders200ResponseResultsARFlatrateInner}", )
OpenAPI.property_type(::Type{ TvSeasonWatchProviders200ResponseResultsNO }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonWatchProviders200ResponseResultsNO[name]))}

function check_required(o::TvSeasonWatchProviders200ResponseResultsNO)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonWatchProviders200ResponseResultsNO }, name::Symbol, val)
end
