# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_CH

    MovieWatchProviders200ResponseResultsCH(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsCHBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsCHBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsCH <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCHBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCHBuyInner} }

    function MovieWatchProviders200ResponseResultsCH(link, flatrate, buy, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCH, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCH, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCH, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCH, Symbol("rent"), rent)
        return new(link, flatrate, buy, rent, )
    end
end # type MovieWatchProviders200ResponseResultsCH

const _property_types_MovieWatchProviders200ResponseResultsCH = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsCHBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsCHBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsCH }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsCH[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsCH)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsCH }, name::Symbol, val)
end
