# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""person_combined_credits_200_response

    PersonCombinedCredits200Response(;
        cast=nothing,
        crew=nothing,
        id=0,
    )

    - cast::Vector{PersonCombinedCredits200ResponseCastInner}
    - crew::Vector{PersonCombinedCredits200ResponseCrewInner}
    - id::Int64
"""
Base.@kwdef mutable struct PersonCombinedCredits200Response <: OpenAPI.APIModel
    cast::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonCombinedCredits200ResponseCastInner} }
    crew::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonCombinedCredits200ResponseCrewInner} }
    id::Union{Nothing, Int64} = 0

    function PersonCombinedCredits200Response(cast, crew, id, )
        OpenAPI.validate_property(PersonCombinedCredits200Response, Symbol("cast"), cast)
        OpenAPI.validate_property(PersonCombinedCredits200Response, Symbol("crew"), crew)
        OpenAPI.validate_property(PersonCombinedCredits200Response, Symbol("id"), id)
        return new(cast, crew, id, )
    end
end # type PersonCombinedCredits200Response

const _property_types_PersonCombinedCredits200Response = Dict{Symbol,String}(Symbol("cast")=>"Vector{PersonCombinedCredits200ResponseCastInner}", Symbol("crew")=>"Vector{PersonCombinedCredits200ResponseCrewInner}", Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ PersonCombinedCredits200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonCombinedCredits200Response[name]))}

function check_required(o::PersonCombinedCredits200Response)
    true
end

function OpenAPI.validate_property(::Type{ PersonCombinedCredits200Response }, name::Symbol, val)
end
