# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_PT

    MovieWatchProviders200ResponseResultsPT(;
        link=nothing,
        buy=nothing,
        rent=nothing,
        flatrate=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsPERentInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsPTRentInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsPT <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsPERentInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsPTRentInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner} }

    function MovieWatchProviders200ResponseResultsPT(link, buy, rent, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPT, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPT, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPT, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsPT, Symbol("flatrate"), flatrate)
        return new(link, buy, rent, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsPT

const _property_types_MovieWatchProviders200ResponseResultsPT = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsPERentInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsPTRentInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsPT }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsPT[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsPT)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsPT }, name::Symbol, val)
end
