# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""alternative_names_copy_200_response

    AlternativeNamesCopy200Response(;
        id=0,
        logos=nothing,
    )

    - id::Int64
    - logos::Vector{AlternativeNamesCopy200ResponseLogosInner}
"""
Base.@kwdef mutable struct AlternativeNamesCopy200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    logos::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{AlternativeNamesCopy200ResponseLogosInner} }

    function AlternativeNamesCopy200Response(id, logos, )
        OpenAPI.validate_property(AlternativeNamesCopy200Response, Symbol("id"), id)
        OpenAPI.validate_property(AlternativeNamesCopy200Response, Symbol("logos"), logos)
        return new(id, logos, )
    end
end # type AlternativeNamesCopy200Response

const _property_types_AlternativeNamesCopy200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("logos")=>"Vector{AlternativeNamesCopy200ResponseLogosInner}", )
OpenAPI.property_type(::Type{ AlternativeNamesCopy200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AlternativeNamesCopy200Response[name]))}

function check_required(o::AlternativeNamesCopy200Response)
    true
end

function OpenAPI.validate_property(::Type{ AlternativeNamesCopy200Response }, name::Symbol, val)
end
