# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response_results_RU

    TvSeriesWatchProviders200ResponseResultsRU(;
        link=nothing,
        flatrate=nothing,
        ads=nothing,
    )

    - link::String
    - flatrate::Vector{TvSeriesWatchProviders200ResponseResultsRUFlatrateInner}
    - ads::Vector{TvSeriesWatchProviders200ResponseResultsRUAdsInner}
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200ResponseResultsRU <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsRUFlatrateInner} }
    ads::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsRUAdsInner} }

    function TvSeriesWatchProviders200ResponseResultsRU(link, flatrate, ads, )
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsRU, Symbol("link"), link)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsRU, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsRU, Symbol("ads"), ads)
        return new(link, flatrate, ads, )
    end
end # type TvSeriesWatchProviders200ResponseResultsRU

const _property_types_TvSeriesWatchProviders200ResponseResultsRU = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{TvSeriesWatchProviders200ResponseResultsRUFlatrateInner}", Symbol("ads")=>"Vector{TvSeriesWatchProviders200ResponseResultsRUAdsInner}", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200ResponseResultsRU }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200ResponseResultsRU[name]))}

function check_required(o::TvSeriesWatchProviders200ResponseResultsRU)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200ResponseResultsRU }, name::Symbol, val)
end
