# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""collection_translations_200_response_translations_inner

    CollectionTranslations200ResponseTranslationsInner(;
        iso_3166_1=nothing,
        iso_639_1=nothing,
        name=nothing,
        english_name=nothing,
        data=nothing,
    )

    - iso_3166_1::String
    - iso_639_1::String
    - name::String
    - english_name::String
    - data::CollectionTranslations200ResponseTranslationsInnerData
"""
Base.@kwdef mutable struct CollectionTranslations200ResponseTranslationsInner <: OpenAPI.APIModel
    iso_3166_1::Union{Nothing, String} = nothing
    iso_639_1::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    english_name::Union{Nothing, String} = nothing
    data = nothing # spec type: Union{ Nothing, CollectionTranslations200ResponseTranslationsInnerData }

    function CollectionTranslations200ResponseTranslationsInner(iso_3166_1, iso_639_1, name, english_name, data, )
        OpenAPI.validate_property(CollectionTranslations200ResponseTranslationsInner, Symbol("iso_3166_1"), iso_3166_1)
        OpenAPI.validate_property(CollectionTranslations200ResponseTranslationsInner, Symbol("iso_639_1"), iso_639_1)
        OpenAPI.validate_property(CollectionTranslations200ResponseTranslationsInner, Symbol("name"), name)
        OpenAPI.validate_property(CollectionTranslations200ResponseTranslationsInner, Symbol("english_name"), english_name)
        OpenAPI.validate_property(CollectionTranslations200ResponseTranslationsInner, Symbol("data"), data)
        return new(iso_3166_1, iso_639_1, name, english_name, data, )
    end
end # type CollectionTranslations200ResponseTranslationsInner

const _property_types_CollectionTranslations200ResponseTranslationsInner = Dict{Symbol,String}(Symbol("iso_3166_1")=>"String", Symbol("iso_639_1")=>"String", Symbol("name")=>"String", Symbol("english_name")=>"String", Symbol("data")=>"CollectionTranslations200ResponseTranslationsInnerData", )
OpenAPI.property_type(::Type{ CollectionTranslations200ResponseTranslationsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CollectionTranslations200ResponseTranslationsInner[name]))}

function check_required(o::CollectionTranslations200ResponseTranslationsInner)
    true
end

function OpenAPI.validate_property(::Type{ CollectionTranslations200ResponseTranslationsInner }, name::Symbol, val)
end
