# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""account_rated_movies_200_response_results_inner_account_rating

    AccountRatedMovies200ResponseResultsInnerAccountRating(;
        created_at=nothing,
        value=0,
    )

    - created_at::String
    - value::Int64
"""
Base.@kwdef mutable struct AccountRatedMovies200ResponseResultsInnerAccountRating <: OpenAPI.APIModel
    created_at::Union{Nothing, String} = nothing
    value::Union{Nothing, Int64} = 0

    function AccountRatedMovies200ResponseResultsInnerAccountRating(created_at, value, )
        OpenAPI.validate_property(AccountRatedMovies200ResponseResultsInnerAccountRating, Symbol("created_at"), created_at)
        OpenAPI.validate_property(AccountRatedMovies200ResponseResultsInnerAccountRating, Symbol("value"), value)
        return new(created_at, value, )
    end
end # type AccountRatedMovies200ResponseResultsInnerAccountRating

const _property_types_AccountRatedMovies200ResponseResultsInnerAccountRating = Dict{Symbol,String}(Symbol("created_at")=>"String", Symbol("value")=>"Int64", )
OpenAPI.property_type(::Type{ AccountRatedMovies200ResponseResultsInnerAccountRating }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountRatedMovies200ResponseResultsInnerAccountRating[name]))}

function check_required(o::AccountRatedMovies200ResponseResultsInnerAccountRating)
    true
end

function OpenAPI.validate_property(::Type{ AccountRatedMovies200ResponseResultsInnerAccountRating }, name::Symbol, val)
end
