# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""authentication_validate_key_200_response

    AuthenticationValidateKey200Response(;
        success=true,
        status_code=0,
        status_message=nothing,
    )

    - success::Bool
    - status_code::Int64
    - status_message::String
"""
Base.@kwdef mutable struct AuthenticationValidateKey200Response <: OpenAPI.APIModel
    success::Union{Nothing, Bool} = true
    status_code::Union{Nothing, Int64} = 0
    status_message::Union{Nothing, String} = nothing

    function AuthenticationValidateKey200Response(success, status_code, status_message, )
        OpenAPI.validate_property(AuthenticationValidateKey200Response, Symbol("success"), success)
        OpenAPI.validate_property(AuthenticationValidateKey200Response, Symbol("status_code"), status_code)
        OpenAPI.validate_property(AuthenticationValidateKey200Response, Symbol("status_message"), status_message)
        return new(success, status_code, status_message, )
    end
end # type AuthenticationValidateKey200Response

const _property_types_AuthenticationValidateKey200Response = Dict{Symbol,String}(Symbol("success")=>"Bool", Symbol("status_code")=>"Int64", Symbol("status_message")=>"String", )
OpenAPI.property_type(::Type{ AuthenticationValidateKey200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AuthenticationValidateKey200Response[name]))}

function check_required(o::AuthenticationValidateKey200Response)
    true
end

function OpenAPI.validate_property(::Type{ AuthenticationValidateKey200Response }, name::Symbol, val)
end
