# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_FR

    MovieWatchProviders200ResponseResultsFR(;
        link=nothing,
        rent=nothing,
        buy=nothing,
        flatrate=nothing,
    )

    - link::String
    - rent::Vector{MovieWatchProviders200ResponseResultsFRRentInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsFRRentInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsFR <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsFRRentInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsFRRentInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }

    function MovieWatchProviders200ResponseResultsFR(link, rent, buy, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFR, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFR, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFR, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsFR, Symbol("flatrate"), flatrate)
        return new(link, rent, buy, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsFR

const _property_types_MovieWatchProviders200ResponseResultsFR = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsFRRentInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsFRRentInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsFR }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsFR[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsFR)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsFR }, name::Symbol, val)
end
