# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response_results_KR

    TvSeriesWatchProviders200ResponseResultsKR(;
        link=nothing,
        flatrate=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsKRBuyInner}
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200ResponseResultsKR <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsKRBuyInner} }

    function TvSeriesWatchProviders200ResponseResultsKR(link, flatrate, )
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsKR, Symbol("link"), link)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsKR, Symbol("flatrate"), flatrate)
        return new(link, flatrate, )
    end
end # type TvSeriesWatchProviders200ResponseResultsKR

const _property_types_TvSeriesWatchProviders200ResponseResultsKR = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsKRBuyInner}", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200ResponseResultsKR }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200ResponseResultsKR[name]))}

function check_required(o::TvSeriesWatchProviders200ResponseResultsKR)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200ResponseResultsKR }, name::Symbol, val)
end
