# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_DE

    MovieWatchProviders200ResponseResultsDE(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsATFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsDEBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsDEBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsDE <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsATFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsDEBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsDEBuyInner} }

    function MovieWatchProviders200ResponseResultsDE(link, flatrate, buy, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsDE, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsDE, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsDE, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsDE, Symbol("rent"), rent)
        return new(link, flatrate, buy, rent, )
    end
end # type MovieWatchProviders200ResponseResultsDE

const _property_types_MovieWatchProviders200ResponseResultsDE = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsATFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsDEBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsDEBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsDE }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsDE[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsDE)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsDE }, name::Symbol, val)
end
