# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_LI

    MovieWatchProviders200ResponseResultsLI(;
        link=nothing,
        flatrate=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsLIFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsLI <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsLIFlatrateInner} }

    function MovieWatchProviders200ResponseResultsLI(link, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsLI, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsLI, Symbol("flatrate"), flatrate)
        return new(link, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsLI

const _property_types_MovieWatchProviders200ResponseResultsLI = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsLIFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsLI }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsLI[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsLI)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsLI }, name::Symbol, val)
end
