# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response_results_LT

    TvSeriesWatchProviders200ResponseResultsLT(;
        link=nothing,
        flatrate=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsLTRentInner}
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200ResponseResultsLT <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsLTRentInner} }

    function TvSeriesWatchProviders200ResponseResultsLT(link, flatrate, )
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsLT, Symbol("link"), link)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsLT, Symbol("flatrate"), flatrate)
        return new(link, flatrate, )
    end
end # type TvSeriesWatchProviders200ResponseResultsLT

const _property_types_TvSeriesWatchProviders200ResponseResultsLT = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsLTRentInner}", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200ResponseResultsLT }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200ResponseResultsLT[name]))}

function check_required(o::TvSeriesWatchProviders200ResponseResultsLT)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200ResponseResultsLT }, name::Symbol, val)
end
