# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_BA

    MovieWatchProviders200ResponseResultsBA(;
        link=nothing,
        buy=nothing,
        flatrate=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsALBuyInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsBA <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsALBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }

    function MovieWatchProviders200ResponseResultsBA(link, buy, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsBA, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsBA, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsBA, Symbol("flatrate"), flatrate)
        return new(link, buy, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsBA

const _property_types_MovieWatchProviders200ResponseResultsBA = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsALBuyInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsBA }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsBA[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsBA)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsBA }, name::Symbol, val)
end
