# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""configuration_jobs_200_response_inner

    ConfigurationJobs200ResponseInner(;
        department=nothing,
        jobs=nothing,
    )

    - department::String
    - jobs::Vector{String}
"""
Base.@kwdef mutable struct ConfigurationJobs200ResponseInner <: OpenAPI.APIModel
    department::Union{Nothing, String} = nothing
    jobs::Union{Nothing, Vector{String}} = nothing

    function ConfigurationJobs200ResponseInner(department, jobs, )
        OpenAPI.validate_property(ConfigurationJobs200ResponseInner, Symbol("department"), department)
        OpenAPI.validate_property(ConfigurationJobs200ResponseInner, Symbol("jobs"), jobs)
        return new(department, jobs, )
    end
end # type ConfigurationJobs200ResponseInner

const _property_types_ConfigurationJobs200ResponseInner = Dict{Symbol,String}(Symbol("department")=>"String", Symbol("jobs")=>"Vector{String}", )
OpenAPI.property_type(::Type{ ConfigurationJobs200ResponseInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConfigurationJobs200ResponseInner[name]))}

function check_required(o::ConfigurationJobs200ResponseInner)
    true
end

function OpenAPI.validate_property(::Type{ ConfigurationJobs200ResponseInner }, name::Symbol, val)
end
