# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""person_tv_credits_200_response

    PersonTvCredits200Response(;
        cast=nothing,
        crew=nothing,
        id=0,
    )

    - cast::Vector{PersonTvCredits200ResponseCastInner}
    - crew::Vector{PersonTvCredits200ResponseCrewInner}
    - id::Int64
"""
Base.@kwdef mutable struct PersonTvCredits200Response <: OpenAPI.APIModel
    cast::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonTvCredits200ResponseCastInner} }
    crew::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonTvCredits200ResponseCrewInner} }
    id::Union{Nothing, Int64} = 0

    function PersonTvCredits200Response(cast, crew, id, )
        OpenAPI.validate_property(PersonTvCredits200Response, Symbol("cast"), cast)
        OpenAPI.validate_property(PersonTvCredits200Response, Symbol("crew"), crew)
        OpenAPI.validate_property(PersonTvCredits200Response, Symbol("id"), id)
        return new(cast, crew, id, )
    end
end # type PersonTvCredits200Response

const _property_types_PersonTvCredits200Response = Dict{Symbol,String}(Symbol("cast")=>"Vector{PersonTvCredits200ResponseCastInner}", Symbol("crew")=>"Vector{PersonTvCredits200ResponseCrewInner}", Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ PersonTvCredits200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonTvCredits200Response[name]))}

function check_required(o::PersonTvCredits200Response)
    true
end

function OpenAPI.validate_property(::Type{ PersonTvCredits200Response }, name::Symbol, val)
end
