# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response_results_JP

    TvSeriesWatchProviders200ResponseResultsJP(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - flatrate::Vector{TvSeriesWatchProviders200ResponseResultsJPFlatrateInner}
    - buy::Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner}
    - rent::Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner}
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200ResponseResultsJP <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsJPFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner} }

    function TvSeriesWatchProviders200ResponseResultsJP(link, flatrate, buy, rent, )
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsJP, Symbol("link"), link)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsJP, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsJP, Symbol("buy"), buy)
        OpenAPI.validate_property(TvSeriesWatchProviders200ResponseResultsJP, Symbol("rent"), rent)
        return new(link, flatrate, buy, rent, )
    end
end # type TvSeriesWatchProviders200ResponseResultsJP

const _property_types_TvSeriesWatchProviders200ResponseResultsJP = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{TvSeriesWatchProviders200ResponseResultsJPFlatrateInner}", Symbol("buy")=>"Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner}", Symbol("rent")=>"Vector{TvSeriesWatchProviders200ResponseResultsJPBuyInner}", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200ResponseResultsJP }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200ResponseResultsJP[name]))}

function check_required(o::TvSeriesWatchProviders200ResponseResultsJP)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200ResponseResultsJP }, name::Symbol, val)
end
