# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_screened_theatrically_200_response

    TvSeriesScreenedTheatrically200Response(;
        id=0,
        results=nothing,
    )

    - id::Int64
    - results::Vector{TvSeriesScreenedTheatrically200ResponseResultsInner}
"""
Base.@kwdef mutable struct TvSeriesScreenedTheatrically200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    results::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesScreenedTheatrically200ResponseResultsInner} }

    function TvSeriesScreenedTheatrically200Response(id, results, )
        OpenAPI.validate_property(TvSeriesScreenedTheatrically200Response, Symbol("id"), id)
        OpenAPI.validate_property(TvSeriesScreenedTheatrically200Response, Symbol("results"), results)
        return new(id, results, )
    end
end # type TvSeriesScreenedTheatrically200Response

const _property_types_TvSeriesScreenedTheatrically200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("results")=>"Vector{TvSeriesScreenedTheatrically200ResponseResultsInner}", )
OpenAPI.property_type(::Type{ TvSeriesScreenedTheatrically200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesScreenedTheatrically200Response[name]))}

function check_required(o::TvSeriesScreenedTheatrically200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesScreenedTheatrically200Response }, name::Symbol, val)
end
