# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_watch_providers_200_response_results_EG_flatrate_inner

    TvSeasonWatchProviders200ResponseResultsEGFlatrateInner(;
        logo_path=nothing,
        provider_id=0,
        provider_name=nothing,
        display_priority=0,
    )

    - logo_path::String
    - provider_id::Int64
    - provider_name::String
    - display_priority::Int64
"""
Base.@kwdef mutable struct TvSeasonWatchProviders200ResponseResultsEGFlatrateInner <: OpenAPI.APIModel
    logo_path::Union{Nothing, String} = nothing
    provider_id::Union{Nothing, Int64} = 0
    provider_name::Union{Nothing, String} = nothing
    display_priority::Union{Nothing, Int64} = 0

    function TvSeasonWatchProviders200ResponseResultsEGFlatrateInner(logo_path, provider_id, provider_name, display_priority, )
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsEGFlatrateInner, Symbol("logo_path"), logo_path)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsEGFlatrateInner, Symbol("provider_id"), provider_id)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsEGFlatrateInner, Symbol("provider_name"), provider_name)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsEGFlatrateInner, Symbol("display_priority"), display_priority)
        return new(logo_path, provider_id, provider_name, display_priority, )
    end
end # type TvSeasonWatchProviders200ResponseResultsEGFlatrateInner

const _property_types_TvSeasonWatchProviders200ResponseResultsEGFlatrateInner = Dict{Symbol,String}(Symbol("logo_path")=>"String", Symbol("provider_id")=>"Int64", Symbol("provider_name")=>"String", Symbol("display_priority")=>"Int64", )
OpenAPI.property_type(::Type{ TvSeasonWatchProviders200ResponseResultsEGFlatrateInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonWatchProviders200ResponseResultsEGFlatrateInner[name]))}

function check_required(o::TvSeasonWatchProviders200ResponseResultsEGFlatrateInner)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonWatchProviders200ResponseResultsEGFlatrateInner }, name::Symbol, val)
end
