# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""genre_movie_list_200_response

    GenreMovieList200Response(;
        genres=nothing,
    )

    - genres::Vector{GenreMovieList200ResponseGenresInner}
"""
Base.@kwdef mutable struct GenreMovieList200Response <: OpenAPI.APIModel
    genres::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{GenreMovieList200ResponseGenresInner} }

    function GenreMovieList200Response(genres, )
        OpenAPI.validate_property(GenreMovieList200Response, Symbol("genres"), genres)
        return new(genres, )
    end
end # type GenreMovieList200Response

const _property_types_GenreMovieList200Response = Dict{Symbol,String}(Symbol("genres")=>"Vector{GenreMovieList200ResponseGenresInner}", )
OpenAPI.property_type(::Type{ GenreMovieList200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GenreMovieList200Response[name]))}

function check_required(o::GenreMovieList200Response)
    true
end

function OpenAPI.validate_property(::Type{ GenreMovieList200Response }, name::Symbol, val)
end
