# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_changes_200_response

    TvSeriesChanges200Response(;
        changes=nothing,
    )

    - changes::Vector{TvSeriesChanges200ResponseChangesInner}
"""
Base.@kwdef mutable struct TvSeriesChanges200Response <: OpenAPI.APIModel
    changes::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesChanges200ResponseChangesInner} }

    function TvSeriesChanges200Response(changes, )
        OpenAPI.validate_property(TvSeriesChanges200Response, Symbol("changes"), changes)
        return new(changes, )
    end
end # type TvSeriesChanges200Response

const _property_types_TvSeriesChanges200Response = Dict{Symbol,String}(Symbol("changes")=>"Vector{TvSeriesChanges200ResponseChangesInner}", )
OpenAPI.property_type(::Type{ TvSeriesChanges200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesChanges200Response[name]))}

function check_required(o::TvSeriesChanges200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesChanges200Response }, name::Symbol, val)
end
