# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_CL

    MovieWatchProviders200ResponseResultsCL(;
        link=nothing,
        buy=nothing,
        flatrate=nothing,
        rent=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsCLBuyInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsCLBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsCL <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCLBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsARFlatrateInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsCLBuyInner} }

    function MovieWatchProviders200ResponseResultsCL(link, buy, flatrate, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCL, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCL, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCL, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsCL, Symbol("rent"), rent)
        return new(link, buy, flatrate, rent, )
    end
end # type MovieWatchProviders200ResponseResultsCL

const _property_types_MovieWatchProviders200ResponseResultsCL = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsCLBuyInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsARFlatrateInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsCLBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsCL }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsCL[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsCL)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsCL }, name::Symbol, val)
end
