# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_IL

    MovieWatchProviders200ResponseResultsIL(;
        link=nothing,
        buy=nothing,
        flatrate=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsILBuyInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsIL <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsILBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }

    function MovieWatchProviders200ResponseResultsIL(link, buy, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIL, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIL, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsIL, Symbol("flatrate"), flatrate)
        return new(link, buy, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsIL

const _property_types_MovieWatchProviders200ResponseResultsIL = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsILBuyInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsIL }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsIL[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsIL)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsIL }, name::Symbol, val)
end
