# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""collection_translations_200_response

    CollectionTranslations200Response(;
        id=0,
        translations=nothing,
    )

    - id::Int64
    - translations::Vector{CollectionTranslations200ResponseTranslationsInner}
"""
Base.@kwdef mutable struct CollectionTranslations200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    translations::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CollectionTranslations200ResponseTranslationsInner} }

    function CollectionTranslations200Response(id, translations, )
        OpenAPI.validate_property(CollectionTranslations200Response, Symbol("id"), id)
        OpenAPI.validate_property(CollectionTranslations200Response, Symbol("translations"), translations)
        return new(id, translations, )
    end
end # type CollectionTranslations200Response

const _property_types_CollectionTranslations200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("translations")=>"Vector{CollectionTranslations200ResponseTranslationsInner}", )
OpenAPI.property_type(::Type{ CollectionTranslations200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CollectionTranslations200Response[name]))}

function check_required(o::CollectionTranslations200Response)
    true
end

function OpenAPI.validate_property(::Type{ CollectionTranslations200Response }, name::Symbol, val)
end
