# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_watch_providers_200_response_results_PL

    TvSeasonWatchProviders200ResponseResultsPL(;
        link=nothing,
        rent=nothing,
        flatrate=nothing,
    )

    - link::String
    - rent::Vector{TvSeriesWatchProviders200ResponseResultsPLRentInner}
    - flatrate::Vector{TvSeriesWatchProviders200ResponseResultsPLFlatrateInner}
"""
Base.@kwdef mutable struct TvSeasonWatchProviders200ResponseResultsPL <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsPLRentInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TvSeriesWatchProviders200ResponseResultsPLFlatrateInner} }

    function TvSeasonWatchProviders200ResponseResultsPL(link, rent, flatrate, )
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsPL, Symbol("link"), link)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsPL, Symbol("rent"), rent)
        OpenAPI.validate_property(TvSeasonWatchProviders200ResponseResultsPL, Symbol("flatrate"), flatrate)
        return new(link, rent, flatrate, )
    end
end # type TvSeasonWatchProviders200ResponseResultsPL

const _property_types_TvSeasonWatchProviders200ResponseResultsPL = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("rent")=>"Vector{TvSeriesWatchProviders200ResponseResultsPLRentInner}", Symbol("flatrate")=>"Vector{TvSeriesWatchProviders200ResponseResultsPLFlatrateInner}", )
OpenAPI.property_type(::Type{ TvSeasonWatchProviders200ResponseResultsPL }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonWatchProviders200ResponseResultsPL[name]))}

function check_required(o::TvSeasonWatchProviders200ResponseResultsPL)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonWatchProviders200ResponseResultsPL }, name::Symbol, val)
end
