# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_MT

    MovieWatchProviders200ResponseResultsMT(;
        link=nothing,
        flatrate=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - flatrate::Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}
    - buy::Vector{MovieWatchProviders200ResponseResultsALBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsALBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsMT <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner} }
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsALBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsALBuyInner} }

    function MovieWatchProviders200ResponseResultsMT(link, flatrate, buy, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMT, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMT, Symbol("flatrate"), flatrate)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMT, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMT, Symbol("rent"), rent)
        return new(link, flatrate, buy, rent, )
    end
end # type MovieWatchProviders200ResponseResultsMT

const _property_types_MovieWatchProviders200ResponseResultsMT = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsAUFlatrateInner}", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsALBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsALBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsMT }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsMT[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsMT)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsMT }, name::Symbol, val)
end
