# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_MU

    MovieWatchProviders200ResponseResultsMU(;
        link=nothing,
        buy=nothing,
        rent=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsMUBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsMUBuyInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsMU <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsMUBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsMUBuyInner} }

    function MovieWatchProviders200ResponseResultsMU(link, buy, rent, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMU, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMU, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsMU, Symbol("rent"), rent)
        return new(link, buy, rent, )
    end
end # type MovieWatchProviders200ResponseResultsMU

const _property_types_MovieWatchProviders200ResponseResultsMU = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsMUBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsMUBuyInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsMU }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsMU[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsMU)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsMU }, name::Symbol, val)
end
