# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_series_watch_providers_200_response

    TvSeriesWatchProviders200Response(;
        id=0,
        results=nothing,
    )

    - id::Int64
    - results::TvSeriesWatchProviders200ResponseResults
"""
Base.@kwdef mutable struct TvSeriesWatchProviders200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    results = nothing # spec type: Union{ Nothing, TvSeriesWatchProviders200ResponseResults }

    function TvSeriesWatchProviders200Response(id, results, )
        OpenAPI.validate_property(TvSeriesWatchProviders200Response, Symbol("id"), id)
        OpenAPI.validate_property(TvSeriesWatchProviders200Response, Symbol("results"), results)
        return new(id, results, )
    end
end # type TvSeriesWatchProviders200Response

const _property_types_TvSeriesWatchProviders200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("results")=>"TvSeriesWatchProviders200ResponseResults", )
OpenAPI.property_type(::Type{ TvSeriesWatchProviders200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeriesWatchProviders200Response[name]))}

function check_required(o::TvSeriesWatchProviders200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvSeriesWatchProviders200Response }, name::Symbol, val)
end
