# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_external_ids_200_response

    TvSeasonExternalIds200Response(;
        id=0,
        freebase_mid=nothing,
        freebase_id=nothing,
        tvdb_id=0,
        tvrage_id=nothing,
        wikidata_id=nothing,
    )

    - id::Int64
    - freebase_mid::String
    - freebase_id::String
    - tvdb_id::Int64
    - tvrage_id::Any
    - wikidata_id::String
"""
Base.@kwdef mutable struct TvSeasonExternalIds200Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    freebase_mid::Union{Nothing, String} = nothing
    freebase_id::Union{Nothing, String} = nothing
    tvdb_id::Union{Nothing, Int64} = 0
    tvrage_id::Union{Nothing, Any} = nothing
    wikidata_id::Union{Nothing, String} = nothing

    function TvSeasonExternalIds200Response(id, freebase_mid, freebase_id, tvdb_id, tvrage_id, wikidata_id, )
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("id"), id)
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("freebase_mid"), freebase_mid)
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("freebase_id"), freebase_id)
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("tvdb_id"), tvdb_id)
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("tvrage_id"), tvrage_id)
        OpenAPI.validate_property(TvSeasonExternalIds200Response, Symbol("wikidata_id"), wikidata_id)
        return new(id, freebase_mid, freebase_id, tvdb_id, tvrage_id, wikidata_id, )
    end
end # type TvSeasonExternalIds200Response

const _property_types_TvSeasonExternalIds200Response = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("freebase_mid")=>"String", Symbol("freebase_id")=>"String", Symbol("tvdb_id")=>"Int64", Symbol("tvrage_id")=>"Any", Symbol("wikidata_id")=>"String", )
OpenAPI.property_type(::Type{ TvSeasonExternalIds200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonExternalIds200Response[name]))}

function check_required(o::TvSeasonExternalIds200Response)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonExternalIds200Response }, name::Symbol, val)
end
