# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_changes_by_id_200_response_changes_inner_items_inner_value

    TvSeasonChangesById200ResponseChangesInnerItemsInnerValue(;
        episode_id=0,
        episode_number=0,
    )

    - episode_id::Int64
    - episode_number::Int64
"""
Base.@kwdef mutable struct TvSeasonChangesById200ResponseChangesInnerItemsInnerValue <: OpenAPI.APIModel
    episode_id::Union{Nothing, Int64} = 0
    episode_number::Union{Nothing, Int64} = 0

    function TvSeasonChangesById200ResponseChangesInnerItemsInnerValue(episode_id, episode_number, )
        OpenAPI.validate_property(TvSeasonChangesById200ResponseChangesInnerItemsInnerValue, Symbol("episode_id"), episode_id)
        OpenAPI.validate_property(TvSeasonChangesById200ResponseChangesInnerItemsInnerValue, Symbol("episode_number"), episode_number)
        return new(episode_id, episode_number, )
    end
end # type TvSeasonChangesById200ResponseChangesInnerItemsInnerValue

const _property_types_TvSeasonChangesById200ResponseChangesInnerItemsInnerValue = Dict{Symbol,String}(Symbol("episode_id")=>"Int64", Symbol("episode_number")=>"Int64", )
OpenAPI.property_type(::Type{ TvSeasonChangesById200ResponseChangesInnerItemsInnerValue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonChangesById200ResponseChangesInnerItemsInnerValue[name]))}

function check_required(o::TvSeasonChangesById200ResponseChangesInnerItemsInnerValue)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonChangesById200ResponseChangesInnerItemsInnerValue }, name::Symbol, val)
end
