# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""tv_season_details_200_response_episodes_inner_crew_inner

    TvSeasonDetails200ResponseEpisodesInnerCrewInner(;
        department=nothing,
        job=nothing,
        credit_id=nothing,
        adult=true,
        gender=0,
        id=0,
        known_for_department=nothing,
        name=nothing,
        original_name=nothing,
        popularity=0,
        profile_path=nothing,
    )

    - department::String
    - job::String
    - credit_id::String
    - adult::Bool
    - gender::Int64
    - id::Int64
    - known_for_department::String
    - name::String
    - original_name::String
    - popularity::Float64
    - profile_path::String
"""
Base.@kwdef mutable struct TvSeasonDetails200ResponseEpisodesInnerCrewInner <: OpenAPI.APIModel
    department::Union{Nothing, String} = nothing
    job::Union{Nothing, String} = nothing
    credit_id::Union{Nothing, String} = nothing
    adult::Union{Nothing, Bool} = true
    gender::Union{Nothing, Int64} = 0
    id::Union{Nothing, Int64} = 0
    known_for_department::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    original_name::Union{Nothing, String} = nothing
    popularity::Union{Nothing, Float64} = 0
    profile_path::Union{Nothing, String} = nothing

    function TvSeasonDetails200ResponseEpisodesInnerCrewInner(department, job, credit_id, adult, gender, id, known_for_department, name, original_name, popularity, profile_path, )
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("department"), department)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("job"), job)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("credit_id"), credit_id)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("adult"), adult)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("gender"), gender)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("id"), id)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("known_for_department"), known_for_department)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("name"), name)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("original_name"), original_name)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("popularity"), popularity)
        OpenAPI.validate_property(TvSeasonDetails200ResponseEpisodesInnerCrewInner, Symbol("profile_path"), profile_path)
        return new(department, job, credit_id, adult, gender, id, known_for_department, name, original_name, popularity, profile_path, )
    end
end # type TvSeasonDetails200ResponseEpisodesInnerCrewInner

const _property_types_TvSeasonDetails200ResponseEpisodesInnerCrewInner = Dict{Symbol,String}(Symbol("department")=>"String", Symbol("job")=>"String", Symbol("credit_id")=>"String", Symbol("adult")=>"Bool", Symbol("gender")=>"Int64", Symbol("id")=>"Int64", Symbol("known_for_department")=>"String", Symbol("name")=>"String", Symbol("original_name")=>"String", Symbol("popularity")=>"Float64", Symbol("profile_path")=>"String", )
OpenAPI.property_type(::Type{ TvSeasonDetails200ResponseEpisodesInnerCrewInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TvSeasonDetails200ResponseEpisodesInnerCrewInner[name]))}

function check_required(o::TvSeasonDetails200ResponseEpisodesInnerCrewInner)
    true
end

function OpenAPI.validate_property(::Type{ TvSeasonDetails200ResponseEpisodesInnerCrewInner }, name::Symbol, val)
end
