# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_details_200_response_genres_inner

    MovieDetails200ResponseGenresInner(;
        id=0,
        name=nothing,
    )

    - id::Int64
    - name::String
"""
Base.@kwdef mutable struct MovieDetails200ResponseGenresInner <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = 0
    name::Union{Nothing, String} = nothing

    function MovieDetails200ResponseGenresInner(id, name, )
        OpenAPI.validate_property(MovieDetails200ResponseGenresInner, Symbol("id"), id)
        OpenAPI.validate_property(MovieDetails200ResponseGenresInner, Symbol("name"), name)
        return new(id, name, )
    end
end # type MovieDetails200ResponseGenresInner

const _property_types_MovieDetails200ResponseGenresInner = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ MovieDetails200ResponseGenresInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieDetails200ResponseGenresInner[name]))}

function check_required(o::MovieDetails200ResponseGenresInner)
    true
end

function OpenAPI.validate_property(::Type{ MovieDetails200ResponseGenresInner }, name::Symbol, val)
end
