# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""movie_watch_providers_200_response_results_SE

    MovieWatchProviders200ResponseResultsSE(;
        link=nothing,
        buy=nothing,
        rent=nothing,
        flatrate=nothing,
    )

    - link::String
    - buy::Vector{MovieWatchProviders200ResponseResultsSEBuyInner}
    - rent::Vector{MovieWatchProviders200ResponseResultsSEBuyInner}
    - flatrate::Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}
"""
Base.@kwdef mutable struct MovieWatchProviders200ResponseResultsSE <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing
    buy::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsSEBuyInner} }
    rent::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsSEBuyInner} }
    flatrate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner} }

    function MovieWatchProviders200ResponseResultsSE(link, buy, rent, flatrate, )
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSE, Symbol("link"), link)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSE, Symbol("buy"), buy)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSE, Symbol("rent"), rent)
        OpenAPI.validate_property(MovieWatchProviders200ResponseResultsSE, Symbol("flatrate"), flatrate)
        return new(link, buy, rent, flatrate, )
    end
end # type MovieWatchProviders200ResponseResultsSE

const _property_types_MovieWatchProviders200ResponseResultsSE = Dict{Symbol,String}(Symbol("link")=>"String", Symbol("buy")=>"Vector{MovieWatchProviders200ResponseResultsSEBuyInner}", Symbol("rent")=>"Vector{MovieWatchProviders200ResponseResultsSEBuyInner}", Symbol("flatrate")=>"Vector{MovieWatchProviders200ResponseResultsBEFlatrateInner}", )
OpenAPI.property_type(::Type{ MovieWatchProviders200ResponseResultsSE }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MovieWatchProviders200ResponseResultsSE[name]))}

function check_required(o::MovieWatchProviders200ResponseResultsSE)
    true
end

function OpenAPI.validate_property(::Type{ MovieWatchProviders200ResponseResultsSE }, name::Symbol, val)
end
